### ISSUE TITLE
centralised Dex Swap indexer

### ISSUE THREAD

**Issue by eli-lim** [JellyfishSDK/jellyfish#1150]
#### What would you like to be added:
- A centralised indexer for `AccountHistory` and possibly more.

#### Why is this needed:
- Legacy-api `/v1/getsubgraphswaps` endpoint is very slow due to getaccounthistory rpc bottlenecking.

### Design
- a **centralised** indexing model is needed, where only 1 worker will source accounthistory data from the blocks and write the relevant data to a central, horizontally scalable database.
- The data can then be exposed via a service layer, greatly improving query performance.
- This system / approach can be leveraged for other bottlenecks if they arise.

#### Components
Similar to CQRS
- ETL worker to read from chain and write to db
- Managed db
- Service to expose the data

#### Build items
- [ ] Scaffold of the new app - #1197
- [ ] Implementation of the dex swap indexer - #1203

**Comment by fuxingloh** [comment]
A better title would be Dex Swap indexer?

Since account history involve everything, might be overkill?
