### ISSUE TITLE
fix(jellyfish-api-core): Account history missing some fields for pool rewards

### ISSUE THREAD

**Issue by chanakasameera** [JellyfishSDK/jellyfish#1242]
#### What happened:
The `txn` and `txid` fields are missing in an `AccountHistory` instance returned from pagination for pool rewards (`options.no_rewards = false`) of `listAccountHistory` RPC

#### What you expected to happen:
The `txn` and `txid` fields should be included in the `AccountHistory`

#### How to reproduce it (as minimally and precisely as possible):
Reproduce by adding a test into [packages/jellyfish-api-core/__tests__/category/account/listAccountHistory.test.ts]

#### Anything else we need to know?:
https://github.com/DeFiCh/ain/blob/acd6ce34181f54ab97a45733a6b830961ee1450f/src/masternodes/rpc_accounts.cpp#L65 According to this `rewardhistoryToJSON` method implementation in Ain, The `txn` and `txid` fields are not included

**Comment by ivan-zynesis** [comment]
@chanakasameera AFAIK, these `AccountHistory` are legitimately have neither txid nor txn.

Jellyfish-api-core `listAccountHistory` is forced to have `no_rewards` true as well thus result have non undefined values for these two. Maybe we should close this?
