### ISSUE TITLE
Transaction V2 format is supported on consensus core but not yet tested

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#1366]
#### What would you like to be added:

This branch contains the basic change to allow Transaction V2 Vout to be signed correctly. https://github.com/DeFiCh/jellyfish/tree/fuxingloh/v2-signing

- [x] Add Static Testing
- [x] Add E2E Testing (submit to testcontainers)

/triage accepted
/area packages

**Comment by canonbrother** [comment]
https://github.com/DeFiCh/ain/blob/f3ef5eb41e78e04cf90648bcc0b312ec48171e82/src/primitives/transaction.h#L216-L222

**Comment by canonbrother** [comment]
hi.. @fuxingloh 
what does 1 to 1 and 1 to 2 mean?? eg: `p2wpkh_1_to_1.test`, `p2wpkh_1_to_2.test`??

and regarding test `Add E2E Testing (submit to testcontainers)`
does that mean gonna revert version to 2 in defid??

**Comment by fuxingloh** [comment]
Oh and the reason, why this issue was created is to make sure we're always compatible to support V2 (altho we're on V4, we still support V1, V2, V4) transaction signing because Bitcoin is on V2 now. This allows us to use all the tools in the bitcoin ecosystem.

> https://github.com/fuxingloh/dfi-rawtx-bitcoinjs

**Comment by canonbrother** [comment]
the **e2e** is more tricky
