### ISSUE TITLE
Add another fixture and fix wrong letter for withdrawFromVault DFTX

### ISSUE THREAD

**Issue by cwkang1998** [JellyfishSDK/jellyfish#1398]
Just for knowledge sharing, we need to add at least 3 fixtures for `should bi-directional buffer-object-buffer`
As you copied this from the previous programmer, we can ignore this for now.

_Originally posted by @jingyi2811 in https://github.com/JellyfishSDK/jellyfish/pull/1252#discussion_r859349082_

**Comment by jingyi2811** [comment]
Also, withdrawFromVault uses J. The letter S (0x53) should be changed to J (0x4a).
