### ISSUE TITLE
WriteError: Corruption: corrupted compressed block contents

### ISSUE THREAD

**Issue by sancag** [JellyfishSDK/jellyfish#1480]
Hi

I am trying to run whale on my own and every now and then I get some corruptions. Could be maybe due to node version upgrade?

```
[Nest] 1  - 05/30/2022, 6:56:24 AM     LOG [RPCBlockProvider] Index - hash: c6ccfd5d5bec34352da569ffc36d003d2934c257e0514162ce6b4d5a70eca098 - height: 1922384
[Nest] 1  - 05/30/2022, 6:56:24 AM   ERROR [RPCBlockProvider] failed exceptionally
[Nest] 1  - 05/30/2022, 6:56:24 AM   ERROR [RPCBlockProvider] WriteError: Corruption: corrupted compressed block contents
```

I wonder how to get passed that?

Currently running:
- node: 2.8.0
- whale: 2.45.3

**Comment by fuxingloh** [comment]
/area apps

I don't specifically know what's that error? Maybe your block indexes got corrupted? Did you do a restart?

**Comment by sancag** [comment]
@fuxingloh the full node is running fine. All that changed was an upgrade from 2.7.1 -> 2.8.0. The error is generated by LevelDB. Restarted full node as well as whale but does not seem to recover from that.

I have a snapshot of the leveldb prior to that but it will end up to the same issue once it reaches that block 1922384 for whatever reason.

**Comment by sancag** [comment]
I picked a snapshot from a leveldb that was running against a 2.7.0 node which was running fine. Maybe a side question.
I suppose you take regular snapshots of your whale db. How do you take them?

**Comment by fuxingloh** [comment]
> I picked a snapshot from a leveldb that was running against a 2.7.0 node which was running fine. Maybe a side question. I suppose you take regular snapshots of your whale db. How do you take them?

https://github.com/JellyfishSDK/jellyfish/blob/563f51a5d2a88345cba58c2beb366e82da143f86/apps/whale-api/src/app.configuration.ts#L22

You can specify the location for the whale database with this env, `WHALE_DATABASE_LEVEL_LOCATION`. Simple gzip will work just fine.

**Comment by fuxingloh** [comment]
> @fuxingloh the full node is running fine. All that changed was an upgrade from 2.7.1 -> 2.8.0. The error is generated by LevelDB. Restarted full node as well as whale but does not seem to recover from that.
> 
> I have a snapshot of the leveldb prior to that but it will end up to the same issue once it reaches that block 1922384 for whatever reason.

Both `defid` and `whale` do fail and naturally, they fail more commonly with servers with restricted IO capability. The failure rates are pretty common on Ocean Infrastructure due to amount of nodes we run (~70-120). I suggest you run multiple server for HA and snapshot frequently.

**Comment by sancag** [comment]
> > @fuxingloh the full node is running fine. All that changed was an upgrade from 2.7.1 -> 2.8.0. The error is generated by LevelDB. Restarted full node as well as whale but does not seem to recover from that.
> > I have a snapshot of the leveldb prior to that but it will end up to the same issue once it reaches that block 1922384 for whatever reason.
> 
> Both `defid` and `whale` do fail and naturally, they fail more commonly with servers with restricted IO capability. The failure rates are pretty common on Ocean Infrastructure due to amount of nodes we run (~70-120). I suggest you run multiple server for HA and snapshot frequently.

Thanks that is what I currently do. Since it works now I think we can close this. Thanks for the reply
