### ISSUE TITLE
Populate rewardPct for stock LPs

### ISSUE THREAD

**Issue by dnamurphy** [JellyfishSDK/jellyfish#1482]
#### What would you like to be added:
The percentage distribution of block rewards for stock (ie. DUSD-based) liquidity pools. This should be recorded in the _rewardPct_ attribute under the poolpairs access point.

#### Why is this needed:
The attributes of these assets should mirror the DFI-based LPs (e.g. ETH-DFI). There is no clear way under the API to extract the reward distribution of the stock LPs, whereas there is with DFI-based pools. Given the former are subject to change, it is very useful to have the correct distribution available.

**Comment by fuxingloh** [comment]
https://github.com/JellyfishSDK/whale/pull/869#issuecomment-1129138828
https://github.com/JellyfishSDK/whale/pull/869#issuecomment-1129139649

/assign @canonbrother do you mind working on this?
