### ISSUE TITLE
Whale Indexer continues to fail at block 3077

### ISSUE THREAD

**Issue by lukasosterheider** [JellyfishSDK/jellyfish#1516]
#### What happened:
The Whale indexer continues to fail at block 3077.
I have tried multiple restarts of the defid including a fresh installation.

[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: 7d0918fea5533abc97320398d2ecceb49e6bd79f0c6aa200b51cbbd461ea707c - height: 3068
[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: e102572a4d62f707bb426d8037577360b44705d0bd67a47b8a84f815fc0f5121 - height: 3069
[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: 773058195ba3c40c7d59c083aff867b99c7fee4e392a443462722ab2bb56fc92 - height: 3070
[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: 77df449c83deb3b57eb03457938700aae7c10112a627cadae5df6637bbe7eb35 - height: 3071
[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: 063e6a6b472348fadede53f89ca034df7dba54fc7cd75cef57510cea416b11d6 - height: 3072
[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: 7585ed1a5e2db2c3839bc0c50c8684a78a40adba132ecb3890b602d38a827aff - height: 3073
[Nest] 1  - 06/02/2022, 6:56:32 PM     LOG [RPCBlockProvider] Index - hash: 627f850f30e79455f4f3579bd85476400dd1d768c0317cec72d48008fd485dce - height: 3074
[Nest] 1  - 06/02/2022, 6:56:33 PM     LOG [RPCBlockProvider] Index - hash: 39ba4389833ec78e74f3405f79c6cd6ca009e0703708046e3f22c4d45bb9fee9 - height: 3075
[Nest] 1  - 06/02/2022, 6:56:33 PM     LOG [RPCBlockProvider] Index - hash: 4df2a81597abb56dd9a65582f547dddbcc332bd913ea1a7305c9684c585b9d8b - height: 3076
[Nest] 1  - 06/02/2022, 6:56:33 PM     LOG [RPCBlockProvider] Index - hash: fd8fc5b943fd05e80e0160ba8ae79d6047d2f1808c6226b73ef880a60aab0322 - height: 3077
[Nest] 1  - 06/02/2022, 6:56:33 PM   ERROR [RPCBlockProvider] failed exceptionally
[Nest] 1  - 06/02/2022, 6:56:33 PM   ERROR [RPCBlockProvider] TypeError: Cannot read properties of undefined (reading 'pubKeyHashPrefix')
[Nest] 1  - 06/02/2022, 6:56:33 PM     LOG [RPCBlockProvider] Cleanup - hash: fd8fc5b943fd05e80e0160ba8ae79d6047d2f1808c6226b73ef880a60aab0322 - height: 3077 - status: ERROR
[Nest] 1  - 06/02/2022, 6:56:33 PM     LOG [RPCBlockProvider] Invalidate - hash: fd8fc5b943fd05e80e0160ba8ae79d6047d2f1808c6226b73ef880a60aab0322 - height: 3077
[Nest] 1  - 06/02/2022, 6:56:33 PM     LOG [RPCBlockProvider] Index - hash: fd8fc5b943fd05e80e0160ba8ae79d6047d2f1808c6226b73ef880a60aab0322 - height: 3077

The whale tries to re-do the block over and over again but cannot continue.

#### Anything else we need to know?:
Both, the defid and whale-api run in Docker.

defid version 2.8.0
whale version - multiple incl. latest and 2.45.2

**Comment by fuxingloh** [comment]
I haven't seen this error before, could you provide us with more runtime information such as docker env or params used?

**Comment by lukasosterheider** [comment]
Sure!

Server type: root-server VPS
OS: Debian GNU/Linux 10 (buster)

Docker version 20.10.12, build e91ed57

docker run -v /home/defichain/data:/data -d --network=ocean --rm defi/defichain  defid -rpcallowip=172.19.0.0/16 -rpcbind=0.0.0.0 -rpcuser=test-user -rpcpassword=test-password

docker run -d -p 127.0.0.1:81:3000 --network=ocean --env WHALE_DEFID_URL=http://test-user:test-password@172.19.0.3:8554  ghcr.io/jellyfishsdk/whale-api

**Comment by fuxingloh** [comment]
Network must be one of these:
- `--network=mainnet`
- `--network=testnet`
- `--network=devnet`
- `--network=regtest`

**Comment by fuxingloh** [comment]
Probably your defid and whale-api "network" is mismatch. The undefined error looks like it couldn't figure out how to parse `pubKeyHashPrefix` properly given the network is different.

**Comment by fuxingloh** [comment]
You can reference with [docker-compose.yml](https://github.com/JellyfishSDK/jellyfish/blob/main/apps/whale-api/docker-compose.yml) for example

**Comment by lukasosterheider** [comment]
You are right!
By setting WHALE_NETWORK=mainnet the whale-api correctly indexes the block.

Thank you!

**Comment by fuxingloh** [comment]
No worries, I have also created #1519 for us to properly detect the `network` and throw the correct error.

/close
