### ISSUE TITLE
Major Regression for `apps/whale-api` due to untracked objects on TokenMapper & PoolMapper

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#1532]
#### What happened:

> See https://github.com/JellyfishSDK/jellyfish/pull/1528 for temporary mitigation. We will work on a fix, a re-index will be required. Please use the preview builds for production with the hot-fixed static code. If you're using a snapshot please use a snapshot earlier than height `1948150`.

The `apps/whale-api` crashed at block height `1948512`.

There is a Major Regression for `apps/whale-api` due to untracked objects on TokenMapper & PoolMapper that affected PoolSwap and CompositeSwap indexing. The bug was due to the stock split mechanism that generated 2 coinbase transactions without its accompanying DfTx to indicate what's the event.

/assign @fuxingloh 
/triage accepted
/priority urgent-now
/area apps
/apps whale-api

**Comment by fuxingloh** [comment]
This also caused 10-15mins downtime on ocean, see https://status.defichain.com/incidents/b15s181nh2j1

**Comment by fuxingloh** [comment]
Please use https://github.com/JellyfishSDK/jellyfish/pkgs/container/whale-api/24365785?tag=88972089d0e439aee173fde0a7fd7cc918c1da79 meanwhile while we work on a proper fix.

**Comment by fuxingloh** [comment]
Currently these indexer contributes to the `TokenMapper`:
- `CreateTokenIndexer`
- `CreatePoolPairIndexer`
- `SetLoanTokenIndexer`

Now we have confirmed, `SetGov` for StockSplit affects it too.

We also need to check if there is any regression with how `LoanToken` get created.

**Comment by sancag** [comment]
Hi, will a complete re-index be required or is it enough to use a snapshot prior to  the failing block?

**Comment by fuxingloh** [comment]
Snapshot prior to `1948150` is enough.

**Comment by fuxingloh** [comment]
> Hi, will a complete re-index be required or is it enough to use a snapshot prior to the failing block?

Apologize for the inconvenience, this was caught on the eleventh hour by @ivan-zynesis (thankfully otherwise it would have been worst).

**Comment by lukasosterheider** [comment]
> Nothing to apologize. This is a complex topic that has not been done before and you guys are super quick in finding a solution.
> 
> Do you know if a snapshot after having reindexed will work with an older version of whale? or is this temporary version (`ghcr.io/jellyfishsdk/whale-api:88972089d0e439aee173fde0a7fd7cc918c1da79`) required?

Reindex of the node is not required to my experience.
Just a reindex of the whale database with the temporary whale version. Therefore, a snapshot/backup of the whale database can be used.

**Comment by sancag** [comment]
I can confirm. A whale db restore with the new temporary whale version has cured the issue. My instance is up and running again!

**Comment by fuxingloh** [comment]
Attached blockchain stock split logs: https://gist.github.com/fuxingloh/5678745aa6eba9770f211c362f96d846

/cc @canonbrother @eli-lim if it helps with #1533 and whale-indexer

**Comment by sancag** [comment]
@fuxingloh just saw the new release which requires a complete re-index. Any snapshots around? Otherwise I will start now syncing from scratch which takes a few days.

**Comment by fuxingloh** [comment]
> @fuxingloh just saw the new release which requires a complete re-index. Any snapshots around? Otherwise I will start now syncing from scratch which takes a few days.

Sadly no; the snapshot system we use is automated in a closed-loop volume environment with limited access.

**Comment by fuxingloh** [comment]
This issue has been fixed and tested with the release of [`v2.47.0`](https://github.com/JellyfishSDK/jellyfish/releases/tag/v2.47.0). It requires "re-indexing", as the `v2.47.0` whale-api index is not guaranteed to be compatible with any version prior. Please regenerate `/data` (deleting the folder) by re-indexing from scratch.

Thanks to @canonbrother and @eli-lim for working on the various issues caused by the regression.
