### ISSUE TITLE
Workflow `release-apps.yml` should also post the full hash of the image

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#1543]
> @fuxingloh is this the temp fix on https://github.com/JellyfishSDK/jellyfish/pkgs/container/whale-api/24365785?tag=88972089d0e439aee173fde0a7fd7cc918c1da79?

Yes it is, but as we update/rebase this PR new container get created with new hash.

_Originally posted by @fuxingloh in https://github.com/JellyfishSDK/jellyfish/issues/1528#issuecomment-1151929617_

---
The workflow:
https://github.com/JellyfishSDK/jellyfish/blob/f166b6b5c326b2331bdc78f6d8cfbaf2084b9b30/.github/workflows/release-apps.yml#L71-L76

- should also post the full hash of the image when it updates the "comment". When new commits get pushed, the `pr-n` will be the defacto mutable preview of this current PR. However, for deployment & testing's sake, we need an immutability hash that is tied to a commit hash to always represent a preview at that time.

/kind feature
/triage accepted
/assign @kodemon
/area workflow
/priority important-soon

**Comment by kodemon** [comment]
Having looked through the issue it seems we want to achieve a QOL update to be able to figure out what container is spawned from a commit at a given time.

Currently each container that is spawned from a commit updates our PR report message with the updated new hash. This is presented as a short hash in the report but if we look at the raw format of the message it should be the full hash. This hash is used to tag the container that got built from it.

From here its possible to look at the edit history of the report to get to the different hashes.

<img width="636" alt="edit-history" src="https://user-images.githubusercontent.com/1998130/173012205-f4cd1704-d2e9-4837-bdcb-297c608172eb.png">

Then entering a message we get access to the full hash _(which is used as a tag)_ to locate the corresponding historic container.

![commit-hash-tag](https://user-images.githubusercontent.com/1998130/173012348-756c8d0f-4c7a-47a2-9bb8-6cf8b69d167c.png)

![container](https://user-images.githubusercontent.com/1998130/173012527-a9196746-504e-474e-99c6-4e223e364e4b.png)

I think I see a potential benefit in giving easier access to historic updates throughout a PR. Not sure about the best representation for this yet, but currently the full hash is currently available albeit a little obfuscated 🤔

**Comment by fuxingloh** [comment]
Hmm, 

How about adding a simple comment stating: "you can also get an immutable image with the commit hash `ghcr.io/jellyfishsdk/[apps]:abcdef....`"?

**Comment by kodemon** [comment]
I think we have a few pathways, a few ideas could be:

 - Add a general additional message informing of the ability to get a specific commit `snapshot` using your above example.

 - Update the report but conserve history. Eg. when a new container is built under the PR take the previous commit hash that was used to tag and keep it in the report.
 
 ```md
Built with commit A

ghcr.io/jellyfishsdk/legacy-api:hash
ghcr.io/jellyfishsdk/ocean-api:hash
ghcr.io/jellyfishsdk/playground-api:hash
ghcr.io/jellyfishsdk/status-api:hash
ghcr.io/jellyfishsdk/whale-api:hash

Built with commit B

ghcr.io/jellyfishsdk/legacy-api:pr-1528
ghcr.io/jellyfishsdk/ocean-api:pr-1528
ghcr.io/jellyfishsdk/playground-api:pr-1528
ghcr.io/jellyfishsdk/status-api:pr-1528
ghcr.io/jellyfishsdk/whale-api:pr-1528
 ```
 
 This would potentially get pretty bloated, but you have a clear trail of containers related to specific commits within the PR.
 
  - Instead of updating the report, create a new report for each commit retaining the history for every build that has occurred within a PR through new comments.
    - In addition to this we can have a first time report with the PR tag like we do now, and have a subsequent comment with just the commit hash version for every container built.

**Comment by fuxingloh** [comment]
The first option seems sound, 2nd, and 3rd would make it bloated.
