### ISSUE TITLE
Remove TokenMapper & PoolPairMappers and its indexer, using Cached RPC to resolve Token & PoolPair

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#1544]
> Following the https://github.com/JellyfishSDK/jellyfish/issues/1532 regression, looking at simplification of Token & PoolPair Mapper design.

#### What would you like to be added:

Given that `TokenMapper` and `PoolPairMapper` were created solely for `PoolSwapIndexer` and its continuous regression battle. I propose we remove the indexing of Token and PoolPair and just resolve them via "Cached RPC Service".

We can remove 4 indexers:
1. CreateTokenIndexer
1. CreatePoolPairIndexer
1. UpdatePoolPairIndexer
1. SetLoanTokenIndexer

And 3 mappers:

1. TokenMapper
1. PoolPairHistoryMapper
1. PoolPairTokenMapper

#### Why is this needed:

Battling change and regression on defid is a uphill battle, requiring our `whale-api` indexer to always be up to date is resource-intensive. Similar to #1533, this change further makes `whale-api` more little weight and resistant to upstream regression.

/triage accepted
/assign @canonbrother 
/priority urgent-now
/area apps
/apps whale-api

**Comment by canonbrother** [comment]
hmm... gonna find pool via fromToken with toToken in compositeSwap
https://github.com/JellyfishSDK/jellyfish/blob/f166b6b5c326b2331bdc78f6d8cfbaf2084b9b30/apps/whale-api/src/module.indexer/model/dftx/composite.swap.ts#L69
