### ISSUE TITLE
getnewaddress RPC Whitelist or REST extension

### ISSUE THREAD

**Issue by MarkCLinovy** [JellyfishSDK/jellyfish#1545]
#### What would you like to be added:
getnewaddress rpc whitelist or Rest extension

#### Why is this needed:
I have a use case where i need to generate a new legacy address for a wallet. Is there any reason this is not whitelisted right now? I would also love to contribute if it is just missing and you give me the 'go ahead'

**Comment by fuxingloh** [comment]
All wallet RPCs are not whitelisted since they are a security and implementation risk. From the public API provider perspective, the address generated would not be yours - it belongs to the node.

/area apps
/apps whale-api

**Comment by MarkCLinovy** [comment]
Hi @fuxingloh,

thanks a lot for the quick response. Im really trying to get into defichain and the jellyfish sdk. Unfortunately since I just started a few things are still quite difficult for me to understand.
So there would be no way for me to create a new legacy address from within a javascript client right? Or is there something I haven't seen yet?
