### ISSUE TITLE
Swaps with missing "from" and/or "to" branches

### ISSUE THREAD

**Issue by dknugo** [JellyfishSDK/jellyfish#1578]
Swaps endpoint sometimes returns swaps with missing "to" branches and even missing "from" branches. E.g. on this page (https://ocean.defichain.com/v0/mainnet/poolpairs/61/swaps/verbose?next=001d4b1200000033), txid d7a8807bc3e0aebf5db4b7cd392698a3e3213a2b33738091bf085b24b2d760fb
<img width="295" alt="image" src="https://user-images.githubusercontent.com/18755758/174980006-4de40528-69bb-4d5f-9f59-160077218669.png">

**Comment by fuxingloh** [comment]
Duplicate of https://github.com/JellyfishSDK/jellyfish/issues/1487 where some snapshotted nodes don't have all the account history.

Issue expected to be fixed by `v3.0` of node release.

**Comment by fuxingloh** [comment]
Closing as this should be fixed with https://github.com/DeFiCh/ain/releases/tag/v2.9.3
