### ISSUE TITLE
ERROR [ExceptionInterceptor] TypeError: burnInfo.paybackburn.toNumber is not a function

### ISSUE THREAD

**Issue by rogi-sh** [JellyfishSDK/jellyfish#1589]
#### What happened:
Update to defichain v2.9.0 and jellyfish whale actual release

#### What you expected to happen:

Jellyfish is working 

#### How to reproduce it (as minimally and precisely as possible):
Update to defichain v2.9.0 and jellyfish actual release

**Comment by sancag** [comment]
Same here

Node: 2.9.0
Jellyfish: 2.47.1
