### ISSUE TITLE
wallet `sign-message` implementation

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#505]
> There is currently no `sign-message` option in jellyfish available yet. How do I integrate a `sign-message` feature as soon as possible? - R

In package `jellyfish-crypto` it contains an interface called `EllipticPair`. It provides the interface for an elliptic curve pair to sign and verify the hash. All implementation of `jellyfish-wallet-*` extends `EllipticPair` which provides the same `sign and verify` interfaces for ECC based operations regardless of HD wallet or not.

### the interfaces
https://github.com/DeFiCh/jellyfish/blob/915c1c15f02d2fc081131d6636223122b0b0340a/packages/jellyfish-crypto/src/elliptic.ts#L24-L30

https://github.com/DeFiCh/jellyfish/blob/915c1c15f02d2fc081131d6636223122b0b0340a/packages/jellyfish-crypto/src/elliptic.ts#L32-L37

### e.g. implementations that extend the interfaces

https://github.com/DeFiCh/jellyfish/blob/915c1c15f02d2fc081131d6636223122b0b0340a/packages/jellyfish-wallet-mnemonic/src/hd_node.ts#L77-L85

https://github.com/DeFiCh/jellyfish/blob/915c1c15f02d2fc081131d6636223122b0b0340a/packages/jellyfish-wallet-mnemonic/src/hd_node.ts#L87-L96

To follow the integrate on ain, the c++ base, you need to sign it exactly as such with the same procedure. 

Since `EllipticPair` sign interface signatures are already DER encoded you just need to encode and generate your message hash.

Using bitcoinjs as an example: 
https://github.com/bitcoinjs/bitcoinjs-message/blob/c43430f4c03c292c719e7801e425d887cbdf7464/index.js#L57-L73
```js
function magicHash (message, messagePrefix) {
  messagePrefix = messagePrefix || '\u0018Bitcoin Signed Message:\n'
  if (!Buffer.isBuffer(messagePrefix)) {
    messagePrefix = Buffer.from(messagePrefix, 'utf8')
  }
  if (!Buffer.isBuffer(message)) {
    message = Buffer.from(message, 'utf8')
  }
  const messageVISize = varuint.encodingLength(message.length)
  const buffer = Buffer.allocUnsafe(
    messagePrefix.length + messageVISize + message.length
  )
  messagePrefix.copy(buffer, 0)
  varuint.encode(message.length, buffer, messagePrefix.length)
  message.copy(buffer, messagePrefix.length + messageVISize)
  return hash256(buffer)
}
```

You can get message prefix here:
https://github.com/DeFiCh/jellyfish/blob/915c1c15f02d2fc081131d6636223122b0b0340a/packages/jellyfish-network/src/index.ts#L28-L29

The `"magicHash"` can be passed directly into `EllipticPair.sign(magicHash)`.

**Comment by davidleomay** [comment]
@fuxingloh: Thanks for the detailed explanation, we'll try it out!

**Comment by davidleomay** [comment]
Hey @fuxingloh,
thanks again for your help. You guys did some really nice work on all the different projects!
We were able to sign a message in the wallet and now we would like to verify the signature in our DFX backend using the jellyfish library. Can you give us a hint on how to do this?
Many thanks in advance!

**Comment by fuxingloh** [comment]
To verify a signature you need 3 things.

1. `magicHash`, you should have this since you generated the message
2. `publicKey`, the public key of the address which is part of your message
3. `signature`, as above

https://github.com/DeFiCh/jellyfish/blob/732ba04ee9f0281515273afc20319cf86c4f122b/packages/jellyfish-crypto/src/elliptic.ts#L82

I guess the question at this point is how do you verify the `publicKey` belongs to the address?

We use `jellyfish-wallet` on `DeFiCh/wallet` hence all addresses are encoded using the `Bech32` format.

https://github.com/DeFiCh/jellyfish/blob/732ba04ee9f0281515273afc20319cf86c4f122b/packages/jellyfish-wallet/src/wallet_account.ts#L25-L26

So to verify the authenticity of a signed message signature you need: `publicKey` + `signature` + `magicHash`.
