### ISSUE TITLE
consolidation of ocean/whale/playground/salmon into `DeFiCh/jellyfish`

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#580]
#### What would you like to be added:

Currently, we have 3 projects (ocean, whale, and playground) that are extensions of the jellyfish project. We should consolidate them into a singular code base so we don't need to manage dependencies updates across the ecosystem.

#### Why is this needed:

- better synergy of DeFiChain open source development across concerns
- single versioning
- single source of truth
- single documentation for the entirety via `jellyfish.defichain.com`
- early regression detection

/assign @fuxingloh 
/triage accepted

**Comment by 0ptim** [comment]
Does this mean that in the future, there will be one large SDK for calling RPC with a local full node as well as calling the ocean API or will these still be separate SDKs/libraries?

**Comment by fuxingloh** [comment]
> Does this mean that in the future, there will be one large SDK for calling RPC with a local full node as well as calling the ocean API or will these still be separate SDKs/libraries?

Yup, one large SDK/Ecosystem that is divided into multiple smaller pieces within itself.
