### ISSUE TITLE
Greenfield Indexer Implementation on top of Jellyfish

### ISSUE THREAD

**Issue by monstrobishi** [JellyfishSDK/jellyfish#933]
#### What would you like to be added:

Basic functionality:
- Indexer with some utlity e.g. "Script aggregator"
- Includes client code, tests and controller, end to end

Requirements:
- Auto-invalidate based on height
- SQLite database

#### Why is this needed:

Migrate whale indexer functionality into Jellyfish

**Comment by monstrobishi** [comment]
https://knexjs.org/#Builder-select

Good typescript support

**Comment by monstrobishi** [comment]
Delete on cascade

https://www.techonthenet.com/sqlite/foreign_keys/foreign_delete.php

**Comment by monstrobishi** [comment]
https://www.npmjs.com/package/graphql-knex-resolver

**Comment by monstrobishi** [comment]
After further investigation although Knex has good maturity and support, it lacks a mature graph QL middleware, so I will proceed with sequelize + https://www.npmjs.com/package/graphql-sequelize

**Comment by ivan-zynesis** [comment]
> Delete on cascade
> 
> https://www.techonthenet.com/sqlite/foreign_keys/foreign_delete.php

Underlying, this is basically make every single table must have height/block as an unique index. Should save us quite some trouble. In order to achieve this, I think we should do always NO MUTATE, append only.

Side nodes, due to we have something like "delayed" / "deferred" action, most likely we need the `n` (the index of txn in the block as part of the main index too)

**Comment by fuxingloh** [comment]
> > Delete on cascade
> > https://www.techonthenet.com/sqlite/foreign_keys/foreign_delete.php
> 
> Underlying, this is basically make every single table must have height/block as an unique index. Should save us quite some trouble. In order to achieve this, I think we should do always NO MUTATE, append only.
> 
> Side nodes, due to we have something like "delayed" / "deferred" action, most likely we need the `n` (the index of txn in the block as part of the main index too)

I would ignore stateful actions that are hard to interpret, focusing on making it lightweight than making it fully featured (aka fully complex).
