### ISSUE TITLE
RFC - `/apps/ocean-api`: RpcController

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#940]
> As part of #580 consolidation efforts. 

#### What would you like to be added:

RpcController implementation on `/apps/ocean-api` pulling whitelisted data from defid remap then exposing it directly for consumers.

#### Why is this needed:

In `whale-api`, when we want to expose a new RPC, we remodel it into RESTful conventions. This requires a RestController, Model interface, and client. Similar to #939, it creates too much work just to expose Data.

This can also be effectively engineered into GraphQLController to expose more data by using a federation of multiple data providers. **Request for comments; to be revisited later with more discussion**.

/sig ecosystem
/area apps packages

**Comment by monstrobishi** [comment]
I think combining into GraphQL controller is ideal, thinking about it from an RPC perspective, GraphQL actually behaves a lot more like RPC than REST does

My original concern was that if we used an off the shelf GraphQL resolver for the Indexer side (e.g. `sequelize-graphql` which resolves whitelisted graph ql directly into SQL), we could have a clash with the RPC resolvers, but we could use https://www.npmjs.com/package/@graphql-tools/merge to merge the Schemas, so that would essentially solve the issue

**Comment by monstrobishi** [comment]
Oh yeah another consideration for GraphQL is built-in caching and the ability to select individual fields

**Comment by monstrobishi** [comment]
For instance on the Defiscan front page it's fetching:
```
data: {id: "4", symbol: "ETH-DFI", displaySymbol: "dETH-DFI", name: "Ether-Default Defi token", status: true,…}
apr: {reward: 0.6430475799667456, total: 0.6430475799667456}
commission: "0.002"
creation: {tx: "9827894c083b77938d13884f0404539daa054a818e0c5019afa1eeff0437a51b", height: 466822}
displaySymbol: "dETH-DFI"
id: "4"
name: "Ether-Default Defi token"
ownerAddress: "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb"
priceRatio: {ab: "0.00091409", ba: "1093.97378715"}
rewardPct: "0.14549"
status: true
symbol: "ETH-DFI"
tokenA: {symbol: "ETH", displaySymbol: "dETH", id: "1", reserve: "8293.28962033", blockCommission: "0"}
tokenB: {symbol: "DFI", displaySymbol: "DFI", id: "0", reserve: "9072641.45390199", blockCommission: "0"}
totalLiquidity: {token: "274117.79848669", usd: "63188314.4839256536727591586975966672"}
tradeEnabled: true
```

For each pool, but the displayed values are only:
```
APR	64.30%
Liquidity	63,469,361 USD
Ratio	1,093.97 DFI/dETH
```

**Comment by fuxingloh** [comment]
> I think combining into GraphQL controller is ideal, thinking about it from an RPC perspective, GraphQL actually behaves a lot more like RPC than REST does
> 
> My original concern was that if we used an off the shelf GraphQL resolver for the Indexer side (e.g. `sequelize-graphql` which resolves whitelisted graph ql directly into SQL), we could have a clash with the RPC resolvers, but we could use https://www.npmjs.com/package/@graphql-tools/merge to merge the Schemas, so that would essentially solve the issue

Yeah, I have the same concerns as you. Largely thinking about how we can properly isolate them. `packages/jellyfish-api-graphql`?

**Comment by monstrobishi** [comment]
After some research into best practices for Nestjs + graphql + typeorm (I think this is a great combo btw), I think that's no longer an issue. The prescribed structures solves that already
