### ISSUE TITLE
RFC & Exploration - `/packages/jellyfish-database`

### ISSUE THREAD

**Issue by fuxingloh** [JellyfishSDK/jellyfish#944]
> As part of the #580 consolidation efforts. 

This is an RFC, it's open for exploration to multiple parties.

#### What would you like to be added:

Greenfield `jellyfish-database` implementation for jellyfish packages usage. We need something embedded, proposing RDMS SQLite as a replacement. Related to #939 and our Indexer implementation.

#### Why is this needed:

> On `DeFiCh/whale` https://github.com/DeFiCh/whale/pull/31, we use a database design with an agnostic provider. Any provider is valid as long as it can conform to the interfaces provided in the Database. For a performant design, the interface uses a log-structured merge-tree (LSM). LSM uses a log data structure with performance characteristics that allow for high write volume which is required for ledger-based applications. This database interface implements a key-value structure with type, index, partition, and sort as key.

And under the hood, we use LevelDB which proves to be **hugely problematic**, while it's performant it's also a custom implementation. Below are some of the problems (non-exclusive):
1. LSM store indexes in separate files making it harder to archive
2. While SortedSetKey is performant, its implementation is mind-boggling for developers at times
3. Lack of atomicity, causing race condition within Whale implementation
4. Less than friendly tooling, can't use traditional RDMS tooling
5. Hard to enforce schema consistency

/area packages
/sig ecosystem

**Comment by monstrobishi** [comment]
I'm pretty much settled on TypeORM at this stage, it's highly compatible with NestJS

**Comment by monstrobishi** [comment]
Plus SQLite of course. Data mapper style

**Comment by ivan-zynesis** [comment]
Self assign this for now.

Starting with trying to setup the docker within `PlaygroundTesting` after read some documentation. Sqlite seems to have enough compatibility with our exploring library, Typeorm and Graphql.
